//! End-to-end golden test: full decode on a tiny model vs the numpy oracle
//! generated by `tools/gen_e2e_golden.py`.
//!
//! Covers: left context padding, RevIN running stats, rolled future
//! covariates, residual block, seq+variate attention with RoPE/QK-norm/
//! PerDimScale, CPM masking, stitching, quantile truncation.

use std::path::PathBuf;

use timesfm3::checkpoint::Safetensors;
use timesfm3::config::ModelConfig;
use timesfm3::json::Json;
use timesfm3::model::timesfm::TimesFM3;
use timesfm3::tensor::Tensor2D;

fn root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("golden/e2e_micro")
}

#[test]
fn full_decode_matches_numpy_oracle() {
    let dir = root();

    // config
    let cfg_bytes = std::fs::read(dir.join("config.json")).expect("config.json");
    let root_json = Json::parse(&cfg_bytes).expect("parse config.json");
    let mut config = ModelConfig::default();
    config.from_config_json(&root_json).expect("overlay config");
    config.validate().expect("config valid");

    // weights
    let store = Safetensors::load(&dir.join("model.safetensors")).expect("load weights");

    // input
    let input = npz_read(&dir.join("input.npz"), "target");
    let horizon = npz_read(&dir.join("input.npz"), "horizon")[0] as usize;
    let context_len = npz_read(&dir.join("input.npz"), "context_len")[0] as usize;

    let model = TimesFM3::load(&store, &config).expect("assemble model");

    // target is (b=1, u=1, C)
    let target = Tensor2D::from_slice(1, context_len, &input).expect("target shape");

    let out = model
        .decode_shaped(
            &target,
            horizon,
            None,
            None,
            None,
            None,
            None,
            None,
            1,
            1,
            context_len,
        )
        .expect("decode");

    // expected: (1, 1, 10, 3)
    let expected = npz_read(&dir.join("expected.npz"), "logits");
    assert_eq!(
        out.data().len(),
        expected.len(),
        "output length {} != expected {}",
        out.data().len(),
        expected.len()
    );

    let mut max_abs = 0.0f32;
    let mut first_bad: Option<(usize, f32, f32)> = None;
    for (i, (&g, &e)) in out.data().iter().zip(&expected).enumerate() {
        let diff = (g - e).abs();
        max_abs = max_abs.max(diff);
        // Tolerance: 1e-3 absolute + 1e-3 relative — numpy oracle uses f32
        // ops in a different order than the Rust engine.
        let allowed = 1e-3 + 1e-3 * e.abs();
        if diff > allowed && first_bad.is_none() {
            first_bad = Some((i, g, e));
        }
    }
    if let Some((i, g, e)) = first_bad {
        eprintln!("rust full output:");
        for (k, v) in out.data().iter().enumerate() {
            eprintln!("{k}: {v:.6}");
        }
        eprintln!("oracle full output:");
        for (k, v) in expected.iter().enumerate() {
            eprintln!("{k}: {v:.6}");
        }
        panic!("element {i}: rust {g} vs oracle {e} (max_abs {max_abs:.3e})");
    }
    println!("e2e oracle diff: max_abs = {max_abs:.3e}");
    assert!(max_abs < 1e-2, "e2e diff too large: {max_abs}");
}

/// Reads a single array entry from an npz file (float32, flat).
fn npz_read(path: &std::path::Path, key: &str) -> Vec<f32> {
    let bytes = std::fs::read(path).expect("read npz");
    // lightweight npz reader using our JSON parser for the zip archive? The
    // npz is a zip; simplest robust path is a tiny ZIP central-directory walk.
    zip_extract_f32(&bytes, key)
}

/// Minimal ZIP central-directory extraction for a single uncompressed member
/// (numpy .npz stores arrays with DEFLATE; fall back to system `unzip` via a
/// temp file if needed). We only need the raw f32 payload.
fn zip_extract_f32(bytes: &[u8], key: &str) -> Vec<f32> {
    // Use the `unzip -p` CLI — present on macOS/Linux; keeps the crate free of
    // zip dependencies.
    let tmp = std::env::temp_dir().join(format!("timesfm3_golden_{}", std::process::id()));
    std::fs::write(&tmp, bytes).expect("write temp npz");
    let out = std::process::Command::new("unzip")
        .arg("-p")
        .arg(&tmp)
        .arg(format!("{key}.npy"))
        .output()
        .expect("run unzip -p");
    let _ = std::fs::remove_file(&tmp);
    assert!(out.status.success(), "unzip failed for {key}");
    let payload = &out.stdout;
    // npy header: magic \x93NUMPY, version byte, then header length
    // (v1: u16 LE at offset 8; v2/v3: u32 LE at offset 8).
    assert_eq!(&payload[0..6], b"\x93NUMPY");
    let header_len = match payload[6] {
        1 => u16::from_le_bytes([payload[8], payload[9]]) as usize,
        2 | 3 => u32::from_le_bytes([payload[8], payload[9], payload[10], payload[11]]) as usize,
        v => panic!("unknown npy version {v}"),
    };
    let data_start = 8 + 2 + header_len;
    payload[data_start..]
        .as_chunks::<4>()
        .0
        .iter()
        .map(|c| f32::from_bits(u32::from_le_bytes([c[0], c[1], c[2], c[3]])))
        .collect()
}
